export const NEW_POST_SUCCESS = 'NEW_POST_SUCCESS'
export const NEW_POST_FAIL = 'NEW_POST_FAIL'
export const NEW_POST_RESET = 'NEW_POST_RESET'

export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS'
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL'

export const LIKEUNLIKE_POST_SUCCESS = 'LIKEUNLIKE_POST_SUCCESS'
export const LIKEUNLIKE_POST_FAIL = 'LIKEUNLIKE_POST_FAIL'

export const UPDATE_CAPTION_SUCCESS = 'UPDATE_CAPTION_SUCCESS'
export const UPDATE_CAPTION_RESET = 'UPDATE_CAPTION_RESET'
export const UPDATE_CAPTION_FAIL = 'UPDATE_CAPTION_FAIL'

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_RESET = 'DELETE_POST_RESET'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL'
export const ADD_COMMENT_RESET = 'ADD_COMMENT_RESET'

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS'
export const DELETE_COMMENT_FAIL = 'DELETE_COMMENT_FAIL'
export const DELETE_COMMENT_RESET = 'DELETE_COMMENT_RESET'


export const CLEAR_ERROR = 'CLEAR_ERROR'